apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ template "fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: AZURE_AUTH_LOCATION
          value: /etc/virtual-kubelet/auth/credentials.json
        - name: ACI_RESOURCE_GROUP
          value: {{ .Values.env.aciResourceGroup }}
        - name: ACI_REGION
          value: {{ default "westus" .Values.env.aciRegion }}
        - name: APISERVER_CERT_LOCATION
          value: /etc/virtual-kubelet/apiservercert/cert.pem
        - name: APISERVER_KEY_LOCATION
          value: /etc/virtual-kubelet/apiserverkey/key.pem
        - name: VKUBELET_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: credentials
          mountPath: "/etc/virtual-kubelet/auth"
          readOnly: true
        - name: apiservercert
          mountPath: "/etc/virtual-kubelet/apiservercert"
          readOnly: true
        - name: apiserverkey
          mountPath: "/etc/virtual-kubelet/apiserverkey"
          readOnly: true
        command: ["virtual-kubelet"]
        args: ["--provider", "azure", "--namespace", "default", "--nodename", {{ default "virtual-kubelet" .Values.env.nodeName | quote }} , "--os", {{ default "Linux" .Values.env.nodeOsType | quote }}, "--taint", {{ default "azure.com/aci" .Values.env.nodeTaint | quote }}]
      volumes:
      - name: credentials
        secret:
          secretName: {{ template "fullname" . }}
      - name: apiservercert
        secret:
          secretName: {{ template "fullname" . }}
      - name: apiserverkey
        secret:
          secretName: {{ template "fullname" . }}
