apiVersion: v1
kind: Pod
metadata:
  name: nano
spec:
  containers:
  - image: microsoft/nanoserver
    imagePullPolicy: Always
    name: nanoserver
    resources:
      requests:
        memory: 4G
        cpu: 2
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    - containerPort: 443
      name: https
  dnsPolicy: Default
<<<<<<< HEAD:examples/iis-pod.yaml
=======
  nodeName: virtual-kubelet-connector-win
>>>>>>> azureReadMe:examples/nanoserver.yaml
  automountServiceAccountToken: false
  tolerations:
  - key: azure.com/aci
    effect: NoSchedule
